url: https://idilkale.github.io
baseurl: 

# Site settings
title: creXRtive
email: your-email@domain.com
description: "Human Computer Interaction Research and Application Lab."


# Team names, titles and social links
people:
- name: Kürşat Çağıltay
  pic: 1
  job: # Rütbenizi buraya yazınız.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Bilgehan Çağıltay
  pic: 2
  job: # Rütbenizi buraya yazınız.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Utku Alkan
  pic: 3
  job: # Rütbenizi buraya yazınız.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sine Mete
  pic: 4
  job: # Rütbenizi buraya yazınız.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: İdil Kale
  pic: 5
  job: # Rütbenizi buraya yazınız.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Faraz Badali Naghadeh
  pic: 6
  job: # Rütbenizi buraya yazınız.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
